package game.interfaceWarhammer;

public enum AttributeEnum {
    POWER, STRENGTH, WEAPON_SKILL, BALLISTIC_SKILL, TOUGHNESS, AGILITY, INTELLIGENCE,
    WILLPOWER, FELLOWSHIP, ATTACKS, HEALTH_POINTS, MOVEMENT, MAGIC
}
